
import { Car } from "@/data/cars";
import { v4 as uuidv4 } from 'uuid';

// Function to generate unique IDs for our placeholder cars
const generateId = () => uuidv4();

// Array of 10 placeholder cars with dummy data
export const placeholderCars: Car[] = [
  {
    id: generateId(),
    make: "Toyota",
    model: "Land Cruiser",
    year: 2023,
    price: 329000,
    mileage: 3450,
    fuelType: "Gasoline",
    transmission: "Automatic",
    location: "Dubai",
    exteriorColor: "Pearl White",
    interiorColor: "Beige",
    vin: "JTMHV05J0D5123456",
    description: "Brand new Toyota Land Cruiser with premium features. This iconic SUV offers exceptional off-road capability, refined luxury, and legendary reliability. Features include premium leather seats, advanced driver assistance systems, and the latest infotainment technology.",
    features: [
      "360° Camera System",
      "Adaptive Cruise Control",
      "Leather Seats",
      "Cooled/Heated Seats",
      "Wireless Charging",
      "JBL Premium Sound",
      "Multi-terrain Select",
      "Panoramic Sunroof"
    ],
    images: [
      "https://images.unsplash.com/photo-1675329648248-21ef7c0311b7?auto=format&fit=crop&q=80&w=1000",
      "https://images.unsplash.com/photo-1571450669798-8acf4f45120f?auto=format&fit=crop&q=80&w=1000",
      "https://images.unsplash.com/photo-1617531653332-bd46c24f2068?auto=format&fit=crop&q=80&w=1000"
    ],
    status: "available",
    bodyType: "SUV",
    engine: "3.5L Twin-Turbo V6",
    drivetrain: "4WD",
    sellerType: "dealer",
    sellerName: "Emirates Motors",
    listedDate: "2023-04-05",
    regionalSpecs: "GCC Specs"
  },
  {
    id: generateId(),
    make: "Mercedes-Benz",
    model: "G-Class",
    year: 2022,
    price: 582000,
    mileage: 12750,
    fuelType: "Gasoline",
    transmission: "Automatic",
    location: "Abu Dhabi",
    exteriorColor: "Obsidian Black",
    interiorColor: "Designo Red",
    vin: "WDCYC7DF9MX123456",
    description: "Immaculate Mercedes-Benz G63 AMG with all the bells and whistles. This iconic luxury SUV combines off-road capability with premium luxury. Features include handcrafted AMG engine, premium Designo interior, and cutting-edge technology.",
    features: [
      "Handcrafted AMG Engine",
      "Designo Interior Package",
      "Burmester Surround Sound",
      "Night Package",
      "Carbon Fiber Trim",
      "360° Camera",
      "Adaptive Suspension",
      "Heated/Ventilated Seats"
    ],
    images: [
      "https://images.unsplash.com/photo-1617469767053-d3b523a0b982?auto=format&fit=crop&q=80&w=1000",
      "https://images.unsplash.com/photo-1581965095463-c2791d563b50?auto=format&fit=crop&q=80&w=1000",
      "https://images.unsplash.com/photo-1608494603682-913a9e8abee9?auto=format&fit=crop&q=80&w=1000"
    ],
    status: "available",
    bodyType: "SUV",
    engine: "4.0L Biturbo V8",
    drivetrain: "4MATIC AWD",
    sellerType: "dealer",
    sellerName: "Mercedes-Benz Abu Dhabi",
    listedDate: "2023-03-18",
    regionalSpecs: "GCC Specs"
  },
  {
    id: generateId(),
    make: "Porsche",
    model: "911 Turbo S",
    year: 2023,
    price: 795000,
    mileage: 1800,
    fuelType: "Gasoline",
    transmission: "PDK",
    location: "Dubai",
    exteriorColor: "GT Silver Metallic",
    interiorColor: "Black/Bordeaux Red",
    vin: "WP0CD2A96KS123456",
    description: "Stunning Porsche 911 Turbo S with Sport Chrono Package. This engineering masterpiece delivers breathtaking performance with everyday usability. The perfect combination of precision engineering, luxury, and heritage.",
    features: [
      "Sport Chrono Package",
      "Burmester High-End Surround Sound",
      "Front Axle Lift System",
      "LED Matrix Headlights",
      "Adaptive Sport Seats Plus",
      "Carbon Ceramic Brakes",
      "Sport Exhaust System",
      "Rear Axle Steering"
    ],
    images: [
      "https://images.unsplash.com/photo-1611651338412-8566f4af4c60?auto=format&fit=crop&q=80&w=1000",
      "https://images.unsplash.com/photo-1580274455191-1c62238fa333?auto=format&fit=crop&q=80&w=1000",
      "https://images.unsplash.com/photo-1570405808766-43e42e5d5bb4?auto=format&fit=crop&q=80&w=1000"
    ],
    status: "available",
    bodyType: "Coupe",
    engine: "3.8L Twin-Turbo Flat-6",
    drivetrain: "AWD",
    sellerType: "dealer",
    sellerName: "Porsche Centre Dubai",
    listedDate: "2023-04-01",
    regionalSpecs: "European Specs"
  },
  {
    id: generateId(),
    make: "Lexus",
    model: "LX 600",
    year: 2023,
    price: 425000,
    mileage: 5600,
    fuelType: "Gasoline",
    transmission: "Automatic",
    location: "Sharjah",
    exteriorColor: "Manganese Luster",
    interiorColor: "Black",
    vin: "JTJHY7AX1M4123456",
    description: "Luxurious Lexus LX 600 with F SPORT package. The flagship Lexus SUV combines extraordinary off-road capability with refined luxury. Features include premium leather, Mark Levinson audio, and advanced safety technologies.",
    features: [
      "F SPORT Package",
      "Mark Levinson Reference Audio",
      "Multi-Terrain Monitor",
      "Dual-Screen Rear Entertainment",
      "Head-Up Display",
      "Active Height Control",
      "Semi-Aniline Leather",
      "Cool Box"
    ],
    images: [
      "https://images.unsplash.com/photo-1669219571842-d30e6789c60c?auto=format&fit=crop&q=80&w=1000",
      "https://images.unsplash.com/photo-1659054768625-457bae1f3a5e?auto=format&fit=crop&q=80&w=1000",
      "https://images.unsplash.com/photo-1639357955726-261a9f245bde?auto=format&fit=crop&q=80&w=1000"
    ],
    status: "available",
    bodyType: "SUV",
    engine: "3.5L Twin-Turbo V6",
    drivetrain: "4WD",
    sellerType: "private",
    sellerName: "Ahmed K.",
    listedDate: "2023-03-25",
    regionalSpecs: "GCC Specs"
  },
  {
    id: generateId(),
    make: "Range Rover",
    model: "Sport",
    year: 2022,
    price: 495000,
    mileage: 9800,
    fuelType: "Diesel",
    transmission: "Automatic",
    location: "Dubai",
    exteriorColor: "Santorini Black",
    interiorColor: "Ebony/Ivory",
    vin: "SALWA2BK7MA123456",
    description: "Elegant Range Rover Sport with Autobiography Dynamic package. This luxury SUV combines outstanding performance with refined comfort. Features include adaptive dynamics, premium Meridian sound system, and panoramic roof.",
    features: [
      "Autobiography Dynamic Package",
      "Meridian Signature Sound System",
      "Adaptive Dynamics",
      "Pixel LED Headlights",
      "24-Way Heated/Cooled Seats",
      "Configurable Ambient Lighting",
      "Electronic Air Suspension",
      "Terrain Response 2"
    ],
    images: [
      "https://images.unsplash.com/photo-1606800052052-a08af7148866?auto=format&fit=crop&q=80&w=1000",
      "https://images.unsplash.com/photo-1539063178763-77c06553b8d6?auto=format&fit=crop&q=80&w=1000",
      "https://images.unsplash.com/photo-1581544571689-544fcc2ef131?auto=format&fit=crop&q=80&w=1000"
    ],
    status: "available",
    bodyType: "SUV",
    engine: "3.0L Inline-6 Diesel",
    drivetrain: "AWD",
    sellerType: "dealer",
    sellerName: "Al Tayer Motors",
    listedDate: "2023-03-15",
    regionalSpecs: "European Specs"
  },
  {
    id: generateId(),
    make: "Bentley",
    model: "Continental GT",
    year: 2022,
    price: 1150000,
    mileage: 3200,
    fuelType: "Gasoline",
    transmission: "Automatic",
    location: "Abu Dhabi",
    exteriorColor: "Glacier White",
    interiorColor: "Linen",
    vin: "SCBCA13S4KC123456",
    description: "Exquisite Bentley Continental GT with Mulliner Driving Specification. This grand tourer represents the pinnacle of British craftsmanship and luxury. Features include handcrafted interior, premium Naim audio, and innovative technology.",
    features: [
      "Mulliner Driving Specification",
      "Naim for Bentley Premium Audio",
      "Rotating Display",
      "Diamond Quilted Seats",
      "Bentley Dynamic Ride",
      "Night Vision",
      "Top View Camera",
      "Head-Up Display"
    ],
    images: [
      "https://images.unsplash.com/photo-1606664685080-4139595fe56f?auto=format&fit=crop&q=80&w=1000",
      "https://images.unsplash.com/photo-1580273257401-71cc5a0d0d73?auto=format&fit=crop&q=80&w=1000",
      "https://images.unsplash.com/photo-1630343710506-89f324c44958?auto=format&fit=crop&q=80&w=1000"
    ],
    status: "available",
    bodyType: "Coupe",
    engine: "6.0L W12 Twin-Turbo",
    drivetrain: "AWD",
    sellerType: "dealer",
    sellerName: "Bentley Abu Dhabi",
    listedDate: "2023-04-02",
    regionalSpecs: "European Specs"
  },
  {
    id: generateId(),
    make: "Nissan",
    model: "Patrol Nismo",
    year: 2023,
    price: 385000,
    mileage: 4500,
    fuelType: "Gasoline",
    transmission: "Automatic",
    location: "Dubai",
    exteriorColor: "Black",
    interiorColor: "Red/Black",
    vin: "JN8AY2NC9P9123456",
    description: "Powerful Nissan Patrol Nismo with performance upgrades. This special edition offers enhanced styling, improved handling, and exclusive features. The ultimate expression of the iconic Patrol with Nismo performance.",
    features: [
      "Nismo Performance Tuning",
      "Exclusive Nismo Styling",
      "Bilstein Shock Absorbers",
      "Nismo Carbon Fiber Trim",
      "Bose Premium Audio",
      "Dual 8\" Entertainment Screens",
      "9\" Infotainment System",
      "Hydraulic Body Motion Control"
    ],
    images: [
      "https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&q=80&w=1000",
      "https://images.unsplash.com/photo-1542230387-bfc77d70e34f?auto=format&fit=crop&q=80&w=1000",
      "https://images.unsplash.com/photo-1606757546736-885c934ba4e8?auto=format&fit=crop&q=80&w=1000"
    ],
    status: "available",
    bodyType: "SUV",
    engine: "5.6L V8",
    drivetrain: "4WD",
    sellerType: "dealer",
    sellerName: "Nissan Arabian Automobiles",
    listedDate: "2023-03-28",
    regionalSpecs: "GCC Specs"
  },
  {
    id: generateId(),
    make: "Audi",
    model: "RS e-tron GT",
    year: 2023,
    price: 675000,
    mileage: 1200,
    fuelType: "Electric",
    transmission: "Automatic",
    location: "Dubai",
    exteriorColor: "Daytona Gray",
    interiorColor: "Black",
    vin: "WAUZZZF15PA123456",
    description: "Innovative Audi RS e-tron GT with Performance Package. This all-electric super sedan offers breathtaking acceleration, long range, and advanced technology. Experience the future of performance driving.",
    features: [
      "Performance Package",
      "Adaptive Air Suspension",
      "Matrix LED Headlights with Laser Light",
      "Bang & Olufsen 3D Sound",
      "Carbon Fiber Trim",
      "Massage Front Seats",
      "Head-Up Display",
      "Night Vision Assistant"
    ],
    images: [
      "https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&q=80&w=1000",
      "https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?auto=format&fit=crop&q=80&w=1000",
      "https://images.unsplash.com/photo-1518987048-93e29699e79a?auto=format&fit=crop&q=80&w=1000"
    ],
    status: "available",
    bodyType: "Sedan",
    engine: "Electric",
    drivetrain: "AWD",
    sellerType: "dealer",
    sellerName: "Audi Dubai",
    listedDate: "2023-04-03",
    regionalSpecs: "European Specs"
  },
  {
    id: generateId(),
    make: "Ferrari",
    model: "Roma",
    year: 2022,
    price: 1050000,
    mileage: 2800,
    fuelType: "Gasoline",
    transmission: "Dual-Clutch",
    location: "Abu Dhabi",
    exteriorColor: "Rosso Corsa",
    interiorColor: "Cuoio",
    vin: "ZFF92YLAXN0123456",
    description: "Stunning Ferrari Roma with premium options. This elegant grand touring coupe offers the perfect balance of performance and luxury. The timeless design is complemented by cutting-edge technology and pure Ferrari performance.",
    features: [
      "Carbon Fiber Racing Seats",
      "JBL Professional Sound System",
      "Advanced Driver Assistance",
      "Carbon Fiber Steering Wheel with LED",
      "Front Lifter System",
      "20\" Forged Diamond Wheels",
      "Adaptive Headlights",
      "Surround View Camera"
    ],
    images: [
      "https://images.unsplash.com/photo-1626668893636-c3f88f2a3558?auto=format&fit=crop&q=80&w=1000",
      "https://images.unsplash.com/photo-1592198084033-aade902d1aae?auto=format&fit=crop&q=80&w=1000",
      "https://images.unsplash.com/photo-1526726538690-5cbf956ae2fd?auto=format&fit=crop&q=80&w=1000"
    ],
    status: "available",
    bodyType: "Coupe",
    engine: "3.9L Twin-Turbo V8",
    drivetrain: "RWD",
    sellerType: "dealer",
    sellerName: "Ferrari Abu Dhabi",
    listedDate: "2023-03-20",
    regionalSpecs: "European Specs"
  },
  {
    id: generateId(),
    make: "Cadillac",
    model: "Escalade ESV",
    year: 2023,
    price: 510000,
    mileage: 5600,
    fuelType: "Gasoline",
    transmission: "Automatic",
    location: "Dubai",
    exteriorColor: "Crystal White Tricoat",
    interiorColor: "Jet Black",
    vin: "1GYS4KKL3PR123456",
    description: "Premium Cadillac Escalade ESV with Platinum Package. This extended-length luxury SUV offers extraordinary space, comfort, and presence. Features include Super Cruise, AKG Studio audio, and innovative technology.",
    features: [
      "Platinum Package",
      "Super Cruise Hands-Free Driving",
      "AKG Studio Reference 36-Speaker Audio",
      "Massage Front & Rear Seats",
      "Night Vision",
      "Rear Seat Entertainment",
      "Panoramic Sunroof",
      "Air Ride Adaptive Suspension"
    ],
    images: [
      "https://images.unsplash.com/photo-1580273957304-47bde1ed6172?auto=format&fit=crop&q=80&w=1000",
      "https://images.unsplash.com/photo-1535732759407-ab0e282e9a0b?auto=format&fit=crop&q=80&w=1000",
      "https://images.unsplash.com/photo-1563720223185-11069f9cd6ed?auto=format&fit=crop&q=80&w=1000"
    ],
    status: "available",
    bodyType: "SUV",
    engine: "6.2L V8",
    drivetrain: "4WD",
    sellerType: "private",
    sellerName: "Mohammed A.",
    listedDate: "2023-03-30",
    regionalSpecs: "American Specs"
  }
];
