// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://quwvbnrtlvdtvelcwqsy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1d3ZibnJ0bHZkdHZlbGN3cXN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxNTkwNTMsImV4cCI6MjA1OTczNTA1M30.oQTaRkZ1quaK-el94QhOBXqjLnda8oET1SPyvh0AKk8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);